# Aprendizagem por Máquinas de Vetores de Suporte (SVM)

A essência desse algoritmo é tentar criar uma linha (parecido com o de regressão logística) que separe perfeitamente os dados, entretanto, esse algoritmo segue o conceito de margem máxima, ou seja, essa linha tem que estar o mais longe possível dos dados mais próximos da linha, criando assim vetores de suporte.

Além disso, devemos prestar atenção num conceito de linearidade e não linearidade. Em alguns datasets bem específicos nós conseguimos separar os dados com uma reta, ou seja, esses datasets são considerados lineares. Mas na maioria dos casos isso não acontece. Para tentar tornar possível a criação de uma reta que separe perfeitamente os dados existem alguns métodos que podemos utilizar. Esses métodos são chamados de Kernel, entre eles existem o linear, gaussiano, polinomial e *radial basis*.

As formas de melhorar a precisão deste algoritmo consiste em achar o kernel mais adequado e aumentar a **punição por previsões incorretas** no algoritmo através do parâmetro custo (C). Nem sempre um C maior significa uma precisão maior. Ademais, achar um C adequado é fundamental, uma vez que quanto maior esse parâmetro maior o custo computacional também.

In [1]:
import pandas as pd 
import numpy as np

base = pd.read_csv('credit_data.csv')
base.loc[base.age < 0, 'age'] = base['age'].mean()

previsores = base.iloc[:, 1:4]
classe = base.iloc[:, 4]

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
previsores = imputer.fit_transform(previsores)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)

from sklearn.model_selection import train_test_split
previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.25, random_state=0)

## Kernel Linear

In [2]:
from sklearn.svm import SVC

classificador = SVC(kernel='linear', random_state=1)
classificador.fit(previsores_treinamento, classe_treinamento)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=1, shrinking=True, tol=0.001,
    verbose=False)

In [3]:
previsoes = classificador.predict(previsores_teste)

In [4]:
from sklearn.metrics import accuracy_score, confusion_matrix
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)
print('Precisão: ', precisao)
print(matriz)

Precisão:  0.946
[[422  14]
 [ 13  51]]


## Kernel Polinomial

In [5]:
classificador = SVC(kernel='poly', random_state=1)
classificador.fit(previsores_treinamento, classe_treinamento)

previsoes = classificador.predict(previsores_teste)

precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)
print('Precisão: ', precisao)
print(matriz)

Precisão:  0.968
[[433   3]
 [ 13  51]]


## Kernel Sigmoide ou Gaussian

In [6]:
classificador = SVC(kernel='sigmoid', random_state=1)
classificador.fit(previsores_treinamento, classe_treinamento)

previsoes = classificador.predict(previsores_teste)

precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)
print('Precisão: ', precisao)
print(matriz)

Precisão:  0.838
[[393  43]
 [ 38  26]]


# Kernel Radial Basis

É o kernel mais utilizado por ser, normalmente, o mais preciso.

In [7]:
classificador = SVC(kernel='rbf', random_state=1) 
classificador.fit(previsores_treinamento, classe_treinamento)

previsoes = classificador.predict(previsores_teste)

precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)
print('Precisão: ', precisao)
print(matriz)

Precisão:  0.982
[[434   2]
 [  7  57]]


Outra coisa que podemos alterar é o custo (C) para tentar aumentar a precisão do algoritmo.

In [8]:
classificador = SVC(C=2.0, kernel='rbf', random_state=1) 
classificador.fit(previsores_treinamento, classe_treinamento)

previsoes = classificador.predict(previsores_teste)

precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)
print('Precisão: ', precisao)
print(matriz)

Precisão:  0.988
[[434   2]
 [  4  60]]


Quanto maior o C, maior o custo computacional. Além disso, podemos perceber que com o C=2 obtivemos um resultado ainda melhor.